### ISSUE TITLE
Add comments hotkey for the Playground

### ISSUE THREAD

**Issue by pluralia** [eclipse-langium/langium-website#109]
The comments hotkey `Cmd` + `/` (`Ctrl` + `/` for Windows) is very common editors feature --- would be cool to have it for the Langium Playground.

**Comment by montymxb** [comment]
I think this is supported in Monaco + Langium as is? @kaisalmen do you know more about this? Or perhaps it's necessary to add additional handling 🤔 . I've also noticed that it doesn't work as expected in Monaco at times, but I swear it did back in Sept. when I was preparing things for MiniLogo in the web.

**Comment by kaisalmen** [comment]
There seem to be issues. CTRL + K works in the build in TypeScript editor, but there also CTRL + / does not work. Seems to be a more general issue. I have to investigate

**Comment by spoenemann** [comment]
It could be related to the general problems of handling keyboard layouts in the browser. We have made quite a lot of effort to get it right in Theia: https://github.com/eclipse-theia/theia/pull/4724

**Comment by montymxb** [comment]
This works now, closing as resolved.
