### ISSUE TITLE
Migrate to GH Pages

### ISSUE THREAD

**Issue by spoenemann** [eclipse-langium/langium-website#179]
The current website uses Netlify. After the move to Eclipse Foundation, we'd like to migrate website deployments to GH Pages. We can use this as example for setting it up: https://github.com/eclipse-sprotty/sprotty-website

**Comment by Lotes** [comment]
@spoenemann Can we close this issue? Looks like it is already done. Or is there something left open?

**Comment by spoenemann** [comment]
Done with #180.
