### ISSUE TITLE
Website is currently unavailable

### ISSUE THREAD

**Issue by mmiller42** [eclipse-langium/langium-website#184]
Just in case you were unaware, the langium.org website seems to be down, with a "could not resolve host" error.

**Comment by spoenemann** [comment]
It's being transferred to Eclipse Foundation: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3578

@eclipsewebmaster what's the state on this?

*Note:* deployment issues should now be reported at the [Eclipse Help Desk](https://gitlab.eclipse.org/eclipsefdn/helpdesk).

**Comment by msujew** [comment]
The website is available again 👍
