### ISSUE TITLE
Domain model showcase: Nested elements are visualized without internals

### ISSUE THREAD

**Issue by JohannesMeierSE** [eclipse-langium/langium-website#194]
@emilkrebs Thanks for the nice visualization of the domain model example!

However, additional the internals of entities and packages inside another package seem not to be rendered (see the attached example). For me, it looks like a bug in the showcase or is this behaviour intentional?

<img width="1517" alt="Screenshot 2023-10-13 at 19 21 49" src="https://github.com/eclipse-langium/langium-website/assets/23192240/68666e35-1592-4e6a-a12b-cb543d43991f">

**Comment by emilkrebs** [comment]
This is intentional, the dotted lines represent inclusive packages so we don't get a infinite tree.

**Comment by emilkrebs** [comment]
This is intentional, the dotted lines represent inclusive packages so we don't get a infinite tree.

**Comment by JohannesMeierSE** [comment]
The Package "complex" does not have dotted lines, and it already shows its new children "Entity" and "Pack", but neither the Attribute "name" of "Entity" nor the dataype "My" ...
