### ISSUE TITLE
Qualified Name Scoping has an error in the code example

### ISSUE THREAD

**Issue by dimitrisfasoulas** [eclipse-langium/langium-website#201]
In the [Qualified Name Scoping](https://langium.org/guides/scoping/qualified-name/) chapter in the code snippets there are two places where modelName is referenced inside a for loop:

```
...
for (const childNode of streamAllContents(document.parseResult.value)) {
...
  exportedDescriptions.push(this.descriptions.createDescription(modelNode, fullyQualifiedName, document));
...
}
```

If I'm not mistaken this should be `childNode `not `modelNode`

**Comment by msujew** [comment]
Yep, seems to be a typo. That should've been `childNode` indeed.
