### ISSUE TITLE
Let the Showcase use the  `Langium AST Helper`

### ISSUE THREAD

**Issue by emilkrebs** [eclipse-langium/langium-website#205]
https://www.npmjs.com/package/langium-ast-helper?activeTab=readme

**Comment by spoenemann** [comment]
@montymxb the npm package is missing metadata about its source repo.

**Comment by montymxb** [comment]
I have the changes locally for adding in the repo metadata & a few other points, I just haven't gotten around to pushing & re-releasing yet, but thanks for reminding me.

**Comment by montymxb** [comment]
Update, changes are up as of last night ✔️
