### ISSUE TITLE
Add a page with API documentation

### ISSUE THREAD

**Issue by aabounegm** [eclipse-langium/langium-website#254]
It would help a lot with exploring Langium and the functionalities it provides if there was a page in the documentation with the whole API exported from Langium. This is easy to do using the JSDoc comments with [TypeDoc](https://typedoc.org/) (I'm already preparing a PR), but some organizational questions need to be answered first.
Since the API documentation is generated from the source code, it should be published on new Langium releases, and not independently in the website repo. However, it should still be linked from the website, leading to the following questions:
1. Should the API docs live on https://langium.org/api or a separate subdomain like https://api.langium.org?
2. If the former, how will it be integrated with the website? Using an iframe or should it be built as part of the website's build process?
3. Do we care about keeping docs for old Langium versions, or just the latest?

**Comment by montymxb** [comment]
I think it would make sense to have a subdomain like `api.langium.org`, and then link to it from our existing documentation.

It would also be great to keep past & current versions, with something `api.langium.org/3.2.0` perhaps.

**Comment by aabounegm** [comment]
Cool, then we can use the GitHub Pages of the langium repo, independent of this one, making the workflow a bit easier. I'll explore how the versioning could be implemented.
