### ISSUE TITLE
Flowchart in docs is broken

### ISSUE THREAD

**Issue by imh** [eclipse-langium/langium-website#256]
At the top of https://langium.org/docs/learn/workflow/ is this graphic:

<img width="492" alt="Flow chart with nodes saying unsupported markdown: list" src="https://github.com/user-attachments/assets/896b6426-4a35-4735-be52-ef88a5a64b47">

It's the first thing you see when you click "Learn" front and center on the home page, so a new user's first impression is 'learning langium is broken.'

As far as I can tell, the culprit is [here](https://github.com/eclipse-langium/langium-website/blob/8461fcbd3cc6bba651c4bfdc1b09073b5232ac1e/hugo/content/docs/learn/workflow/_index.md#L12-L33).

idk anything about mermaid's diagram syntax, but from a quick skim of [the docs](https://mermaid.js.org/syntax/flowchart.html#flowcharts), I don't see semicolons separating lines in the examples, so maybe that's the culprit? no idea really

**Comment by Lotes** [comment]
Fixed by @MarianPalkus, thanks
